### ISSUE TITLE
Mod crashes the game

### ISSUE THREAD

**Issue by Randy624** [asquared31415/ONI-Mods#42] opened 2024-07-31 06:27 UTC
The game does not start with the mod enabled.
![image](https://github.com/user-attachments/assets/f94da21b-bb44-4d5a-8568-3052158ae4aa)

**Comment by asquared31415** [comment] 2024-07-31 19:02
Duplicate of #40, this has been fixed in version 2.0.1. Please use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) to ensure that you have the latest version.

**Closed as not planned by asquared31415** 2024-07-31 19:02 UTC
